# Generated by Django 3.2.5 on 2021-10-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211001_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podpischiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
