# Generated by Django 3.2.5 on 2021-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211006_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Языки',
                'verbose_name_plural': 'языки',
            },
        ),
    ]
