# Generated by Django 3.2.5 on 2021-10-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lang',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
    ]
